//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availabilitytable
    {
        public int aid { get; set; }
        public Nullable<int> emp { get; set; }
        public Nullable<System.DateTime> selectdate { get; set; }
    
        public virtual Emp_Register Emp_Register { get; set; }
    }
}
