//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BookingDetail
    {
        public int BookingID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public string TaxiNumber { get; set; }
        public Nullable<bool> BookingStatus { get; set; }
        public Nullable<bool> Trip { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> CustId { get; set; }
        [DataType(DataType.Date)]
        [Column(TypeName ="date")]
        public System.DateTime StartDate { get; set; }
        public string TaxiModel { get; set; }
    
        public virtual Cust_Register Cust_Register { get; set; }
        public virtual Emp_Register Emp_Register { get; set; }
    }
}
