//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust_Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cust_Register()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.FeedBacks = new HashSet<FeedBack>();
        }
    
        public int CustID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Contact { get; set; }
        public string EmailId { get; set; }
        public string CustAddress { get; set; }
        public int Pincode { get; set; }
        public string CustPasswd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
    }
}
