//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee_Roaster
    {
        public int RoasterID { get; set; }
        public Nullable<int> EmpId { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FromDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
    
        public virtual Emp_Register Emp_Register { get; set; }
    }
}
