//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int feedbackID { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Comments { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> custid { get; set; }
    
        public virtual Cust_Register Cust_Register { get; set; }
        public virtual Emp_Register Emp_Register { get; set; }
    }
}
