//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logintable
    {
        public int UserID { get; set; }
        public string Passwd { get; set; }
        public string Roles { get; set; }
    }
}
