//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTBSWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Availabilitytable> Availabilitytables { get; set; }
        public virtual DbSet<BookingDetail> BookingDetails { get; set; }
        public virtual DbSet<Cust_Register> Cust_Register { get; set; }
        public virtual DbSet<Emp_Register> Emp_Register { get; set; }
        public virtual DbSet<Employee_Roaster> Employee_Roaster { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Logintable> Logintables { get; set; }
        public virtual DbSet<TaxiDetail> TaxiDetails { get; set; }
    }
}
